theme: jekyll-theme-cayman
title: From Magnetic to Optical: NFC-to-Camera Side-Channel Communication via Standards-Compliant Barcodes
description: Cheng Peng, Donghui Dai and Lei Yang, Department of Computing, The Hong Kong Polytechnic University
baseurl: "/NFC2Camera"
titles_from_headings:
  enabled: false
polyu_logo_url: assets/images/polyu-logo.png
polyu_comp_logo_url: assets/images/polyu-comp-logo.png
github:
  repository_url: https://github.com/pc-jack-poly/NFC2Camera